### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [ ]:
import numpy as np
import random

random.seed(42)

# Генерація вектора з використанням random.uniform
vector = np.random.uniform(0, 1, 10)


# Створення матриці
matrix = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])

In [ ]:
# Виведення результатів
print("Вектор:\n", vector)
print("Матриця:\n", matrix)

Вектор:
 [0.2021159  0.11895671 0.6808162  0.70369103 0.45228988 0.26324875
 0.17044462 0.78045417 0.96266992 0.9403321 ]
Матриця:
 [[11 14 17]
 [20 23 26]
 [29 32 35]]


In [ ]:
# Виведення розміру
print("Розмір вектора:", vector.shape)
print("Розмір матриці:", matrix.shape)

Розмір вектора: (10,)
Розмір матриці: (3, 3)


Створено вектор за допомогою модулю random.uniform, розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1.
Створено матрицю розмірністю 3х3 із заданими в умові задачі значеннями.


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [ ]:
# 1
vector_plus_10 = np.round(vector + 10, 2)
print("Вектор після додавання 10 і округлення:")
print(vector_plus_10)

Вектор після додавання 10 і округлення:
[10.2  10.12 10.68 10.7  10.45 10.26 10.17 10.78 10.96 10.94]


In [ ]:
# 2
matrix_times_2 = matrix * 2
print("Матриця після множення на 2:")
print(matrix_times_2)

Матриця після множення на 2:
[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [ ]:
# 3
vector_squared = np.square(vector)
print("Вектор з квадратами кожного елемента vector:")
print(vector_squared)


Вектор з квадратами кожного елемента vector:
[0.04085084 0.0141507  0.4635107  0.49518107 0.20456613 0.0692999
 0.02905137 0.60910871 0.92673338 0.88422446]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [ ]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [ ]:
#1
result_matrix = np.dot(B, A)
print("Резутат множенння матриць B та A:")
print(result_matrix)

Резутат множенння матриць B та A:
[[0.7281 0.5202]
 [0.2034 0.2846]]


Правило таке, що результатом множення матриці розміром  mхn  на матрицю розміром  nхp  є нова матриця розміром  mхp.

Тому, щоб отримати матрицю розмірністю 2х2 у нашому випадку необхідно матрицю B розміром  2х3  помножити на матрицю A розміром  3×2.

In [ ]:
#2
result_matrix_C = np.dot(result_matrix, C)
print("Результат множення матриці result_matrix на вектор C:")
print(result_matrix_C)


Результат множення матриці result_matrix на вектор C:
[[0.5202]
 [0.2846]]


При множенні матриці result_matrix, що має розмірність 2х2 (2 рядки, 2 стовпці) на вектор С, що має розмірність 2х1 (2 рядки, 1 стовпець) ми отримаємо матрицю розміром 2×1 (2 рядки, 1 стовпець).

In [ ]:
#3
result_matrix_D = np.dot(result_matrix, D)
print("Результат множення матриці result_matrix на матрицю D:")
print(result_matrix_D)

Результат множення матриці result_matrix на матрицю D:
[[0.5202 0.7281]
 [0.2846 0.2034]]


Оскільки результатом множення матриці розміром mхn на матрицю розміром nхp є нова матриця розміром mхp, то при множенні матриці result_matrix, що має
розмірність 2х2 на матрицю D, що має розмірність 2х2 ми отримаємо матрицю розміром 2×2.


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [ ]:
#1
print("Оригінальна матриця:")
print(result_matrix)


Оригінальна матриця:
[[0.7281 0.5202]
 [0.2034 0.2846]]


In [ ]:
result_matrix_T = result_matrix.T
print("Транспонована матриця:")
print(result_matrix_T)

Транспонована матриця:
[[0.7281 0.2034]
 [0.5202 0.2846]]


Як бачимо після транспонування рядки з оригінальної матриці перетворились на стовпці у транспонованій і аналогічно стовпці з оригінальної стали рядками у транспонованій матриці.

In [ ]:
#2
print("Оригінальний вектор:")
print(vector)


Оригінальний вектор:
[0.2021159  0.11895671 0.6808162  0.70369103 0.45228988 0.26324875
 0.17044462 0.78045417 0.96266992 0.9403321 ]


In [ ]:
vector_T = vector.T
print("Транспонований вектор:")
print(vector_T)
print("Форма після транспонування:")
print(vector_T.shape)

Транспонований вектор:
[0.2021159  0.11895671 0.6808162  0.70369103 0.45228988 0.26324875
 0.17044462 0.78045417 0.96266992 0.9403321 ]
Форма після транспонування:
(10,)


Висновок: Форма вектора після транспонування не змінюється, тому що він одновимірний.

In [ ]:
#3
column_vector = np.expand_dims(vector, axis = 1)
print("column_vector:")
print(column_vector)
print("Форма column_vector:", column_vector.shape)

column_vector:
[[0.2021159 ]
 [0.11895671]
 [0.6808162 ]
 [0.70369103]
 [0.45228988]
 [0.26324875]
 [0.17044462]
 [0.78045417]
 [0.96266992]
 [0.9403321 ]]
Форма column_vector: (10, 1)


Порівняння:

vector має розмірність (10,)

column_vector має розмірність (10, 1)

Операція numpy.expand_dims додає вимір нашому вектору. Оскільки аргумент axis=1, це перетворює вектор розмірністю (n,) у вектор-стовпець розмірністю (n,1)

Тому тепер ми маємо вектор-стовпець розмірністю 10х1 (10 рядків, 1 стовпець)


In [ ]:
#4
column_vector_T = column_vector.T
print(column_vector_T)
print("Розмірність column_vector_T:", column_vector_T.shape)

[[0.2021159  0.11895671 0.6808162  0.70369103 0.45228988 0.26324875
  0.17044462 0.78045417 0.96266992 0.9403321 ]]
Розмірність column_vector_T: (1, 10)


Транспонування column_vector перетворює його у вектор-рядок із розмірністю (1, 10).